[component]
structures = [ "content_blocks" ]
label = "Page Heading"
description = "Generic page heading"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "My works"
description = "I show only my best works built completely with Craftsmanship,brain,deep work and creativity!"